project:
  type: website
  output-dir: _site

execute:
  freeze: auto

website:
  title: "My Awesome Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog
      - href: book/
        text: Book

format:
  html:
    theme: cosmo
    css: styles.css
