project:
  type: website
  output-dir: _site
  render: 
    - "*.qmd"
    - "!book/"

execute:
  freeze: auto

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog
      - href: book/index.html
        text: Book
        target: _blank

formats:
  html:
    theme: cosmo
    css: styles.css

