project:
  type: website
  output-dir: _site

execute:
  freeze: auto

website:
  title: "My Awesome Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
