project:
  type: website
  output-dir: _site
  render: 
    - "*.qmd"
    - "*.ipynb"
    - "!book/"
  

execute:
  freeze: auto

website:
  title: "Pausa Técnica"
  favicon: "favicon.png"
  site-url: "https://sbat13.github.io"
  image: "logo.png"
  open-graph:
    site-name: "Pausa Técnica"
    locale: pt_PT

  announcement:
    icon: rocket-takeoff-fill
    dismissable: false
    content: "**LIVE** - Lançamento do website!!!"
    type: primary
    position: below-navbar 

  cookie-consent:
    type: implied
    style: simple
    language: pt
    prefs-text: 🍪Cookies
  search:
    location: sidebar
    type: overlay
  
  #navbar:
  #  logo: logo.png
  #  left:
  #    - text: Home
  #      href: index.qmd
  #    - text: Sobre
  #      href: pausa.qmd
  #    - text: Blog
  #      href: blog.qmd
  #    - text: Recursos
  #      href: recursos.qmd
      #- href: book/index.html
      #  stext: Book
      #  target: _blank

  sidebar:
    style: docked
    logo: logo-nobg.png
    #background: white
    contents:
      - text: Sobre
        href: index.qmd
      - text: Blog
        href: posts/index.qmd
      - text: Recursos
        href: recursos/index.qmd
  
  page-footer:
    left: "Made with ♥️ & [Quarto](https://quarto.org)"
    right:
      - text: "&#169; 2025"
      - icon: github
        href: https://github.com/Sbat13
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/sfbatista/
        target: _blank
      - icon: envelope-at-fill
        href: mailto:sbat13@yahoo.com

format:
  html:
    canonical-url: true
    embed-resources: false
    theme: journal
      #light: flatly
      #dark: sketchy
      
    css: [mermaid-colors.css]
    toc: true




