project:
  type: book
  output-dir: ../_site/book   # <- this ensures the book gets built into your site output
book:
  title: "My Book"
  chapters:
    - book/index.qmd
    - book/chapter1.qmd
    - book/chapter2.qmd

format:
  html:
    theme: cosmo
  pdf: 
    documentclass: scrreprt 
