project:
  type: book
  output-dir: ../_site/book   # <- this ensures the book gets built into website output

book:
  title: "My Book"
  sidebar: true
  search: true
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd

format:
  html:
    theme: cosmo
  pdf: 
    documentclass: scrreprt 
