name: Deploy Quarto site to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install uv
        run: |
          curl -Ls https://astral.sh/uv/install.sh | bash
          uv pip install -r pyproject.toml || true  # Safe fallback
      
      - name: Sync environment
        run: uv sync --locked

      - name: Render Quarto Site
        run: quarto render

      - name: Render Quarto Book
        run: |
          cd book
          quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
